name: JSON Schema
on:
  - push
  - pull_request

jobs:
  specs-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run build -- specs

  specs-ietf:
    runs-on: ubuntu-latest
    steps:
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - uses: actions/checkout@v4
      - run: npm run build-ietf
